osx_image: xcode10.2
language: objective-c
cache:
  cocoapods: true
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- pod install || pod install --repo-update
- carthage bootstrap --platform iOS --cache-builds
script:
- mv KartingCoach/GoogleService/.GoogleService-Info-placeholder.plist KartingCoach/GoogleService/GoogleService-Info.plist
- set -o pipefail && xcodebuild test -scheme KartingCoach -sdk iphonesimulator12.2 -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.2' ONLY_ACTIVE_ARCH=NO | xcpretty
